version: '2'

services:
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    image: 'stocker'
    command: >
      gunicorn stocker_app.application:app -b 18.191.156.176:80
    env_file:
      - '.env'
    volumes:
      - '.:/stocker_app'
    ports:
      - '8000:8000'

  celery:
    image: 'stocker'
    command: celery -A stocker_app.stocker_server.tasks.celery_app worker --loglevel=info
    env_file:
      - '.env'
    volumes:
      - '.:/stocker_app'
  
  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
    depends_on:
      - flask

volumes:
  redis:
