version: '2'

services:
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'
    mem_limit: 500m

  stockerapp:
    image: 'quoctrunguit/stocker'
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - '.env'
    volumes:
      - '.:/stocker_app'
    command:  gunicorn stocker_app.application:app -b 0.0.0.0:80 --log-level DEBUG
    mem_limit: 5000m

  celery:
    image: 'quoctrunguit/stocker'
    command: celery worker -A stocker_app.application.celery --loglevel=debug
    env_file:
      - '.env'
    volumes:
      - '.:/stocker_app'
    mem_limit: 5000m

volumes:
  redis:
