FROM continuumio/miniconda3
# Identify the maintainer of an image
LABEL maintainer="quoctrunguit@gmail.com"

COPY ./requirements.txt /app/requirements.txt
WORKDIR /app

RUN apt-get -y update && apt-get -y install gcc
RUN conda install -c conda-forge -y fbprophet
ENV PATH /opt/conda/envs/fbprophet/bin:$PATH
RUN echo "source activate fbprophet" > ~/.bashrc && python3 -m pip install -r requirements.txt